[package]
name = "fulguro_bot"
version = "0.1.0"
authors = ["Arttaaz <arttaaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel      = { version = "*", features = ["sqlite"] }
dirs        = "*"
dotenv      = "*"
serenity    = "*"

# [dependencies.rusqlite]
# version = "0.18.0"
# features = ["bundled"]
