[package]
name = "fulguro_bot"
version = "0.1.0"
authors = ["Arttaaz <arttaaz@gmail.com>", "Jiriakel <jorisvdb96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs        = "*"
fulgurobot_db = "0.2.0"
serenity    = "*"
reqwest        = "*"