name: Rust

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download sqlite
      run: apt install libsqlite3-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
